try:
    pass
except Exception as err:
    pass